<?xml version="1.0" standalone="yes"?>

<?program_dtd version="1"?>

<!DOCTYPE PROGRAM [

<!ELEMENT PROGRAM (DESCRIPTION?,
                   INFO_SOURCE?,
                   PROCESSOR?,
                   COMPILER?,
                   DATATYPES?,
                   MEMORY_MAP?,
                   REGISTER_VALUES?,
                   CODE?,
                   DATA?,
                   EQUATES?,
                   COMMENTS?,
                   PROPERTIES?,
                   BOOKMARKS?,
                   PROGRAM_TREES?,
                   PROGRAM_ENTRY_POINTS?,
                   RELOCATION_TABLE?,
                   SYMBOL_TABLE?,
                   FUNCTIONS?,
                   MARKUP?,
                   EXT_LIBRARY_TABLE?)>
  <!ATTLIST PROGRAM NAME       CDATA #REQUIRED>
  <!ATTLIST PROGRAM EXE_PATH   CDATA #IMPLIED>
  <!ATTLIST PROGRAM EXE_FORMAT CDATA #IMPLIED>
  <!ATTLIST PROGRAM IMAGE_BASE CDATA #IMPLIED>

<!ELEMENT DISPLAY_SETTINGS EMPTY>
  <!ATTLIST DISPLAY_SETTINGS FORMAT           (hex | decimal | octal | binary | char) #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS SIGNED           (y | n)                                 #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS ZERO_PAD         (y | n)                                 #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS ENDIAN           (big | little)                          #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS SHOW_TERMINATOR  (y | n)                                 #IMPLIED>

<!ELEMENT DESCRIPTION    (#PCDATA)>
<!ELEMENT REGULAR_CMT    (#PCDATA)>
<!ELEMENT REPEATABLE_CMT (#PCDATA)>
<!ELEMENT TYPEINFO_CMT   (#PCDATA)>

<!ELEMENT INFO_SOURCE EMPTY>
  <!ATTLIST INFO_SOURCE USER      CDATA #IMPLIED>
  <!ATTLIST INFO_SOURCE TOOL      CDATA #IMPLIED>
  <!ATTLIST INFO_SOURCE FILE      CDATA #IMPLIED>
  <!ATTLIST INFO_SOURCE TIMESTAMP CDATA #IMPLIED>

<!ELEMENT PROCESSOR EMPTY>
  <!ATTLIST PROCESSOR NAME              CDATA          #REQUIRED>
  <!ATTLIST PROCESSOR FAMILY            CDATA          #IMPLIED>
  <!ATTLIST PROCESSOR LANGUAGE_PROVIDER CDATA          #IMPLIED>
  <!ATTLIST PROCESSOR ENDIAN            (big | little) #IMPLIED>
  <!ATTLIST PROCESSOR ADDRESS_MODEL     CDATA          #IMPLIED>

<!-- TODO: expand compiler tag -->
<!ELEMENT COMPILER EMPTY>
  <!ATTLIST COMPILER NAME CDATA #REQUIRED>

<!ELEMENT MEMORY_MAP (MEMORY_SECTION*)>

<!ELEMENT MEMORY_SECTION ((MEMORY_CONTENTS*) | (BIT_MAPPED?))>
  <!ATTLIST MEMORY_SECTION NAME         CDATA                             #REQUIRED>
  <!ATTLIST MEMORY_SECTION START_ADDR   CDATA                             #REQUIRED>
  <!ATTLIST MEMORY_SECTION LENGTH       CDATA                             #REQUIRED>
  <!ATTLIST MEMORY_SECTION PERMISSIONS  (r | w | x | rw | rx | wx | rwx)  #IMPLIED>
  <!ATTLIST MEMORY_SECTION VOLATILE     (y | n)                           #IMPLIED>
  <!ATTLIST MEMORY_SECTION COMMENT      CDATA                             #IMPLIED>

<!ELEMENT MEMORY_CONTENTS EMPTY>
  <!ATTLIST MEMORY_CONTENTS START_ADDR   CDATA  #IMPLIED>
  <!ATTLIST MEMORY_CONTENTS FILE_NAME    CDATA  #REQUIRED>
  <!ATTLIST MEMORY_CONTENTS FILE_OFFSET  CDATA  #REQUIRED>
  <!ATTLIST MEMORY_CONTENTS LENGTH       CDATA  #IMPLIED>

<!ELEMENT BIT_MAPPED EMPTY>
  <!ATTLIST BIT_MAPPED SOURCE_ADDRESS  CDATA  #REQUIRED>

<!ELEMENT REGISTER_VALUES (REGISTER_VALUE_RANGE*)>

<!ELEMENT REGISTER_VALUE_RANGE EMPTY>
  <!ATTLIST REGISTER_VALUE_RANGE REGISTER      CDATA #REQUIRED>
  <!ATTLIST REGISTER_VALUE_RANGE VALUE         CDATA #REQUIRED>
  <!ATTLIST REGISTER_VALUE_RANGE START_ADDRESS CDATA #REQUIRED>
  <!ATTLIST REGISTER_VALUE_RANGE LENGTH        CDATA #REQUIRED>

<!ELEMENT CODE (CODE_BLOCK*)>

<!ELEMENT CODE_BLOCK EMPTY>
  <!ATTLIST CODE_BLOCK  START  CDATA  #REQUIRED>
  <!ATTLIST CODE_BLOCK  END    CDATA  #REQUIRED>

<!ELEMENT DATA (DEFINED_DATA*)>

<!ELEMENT DEFINED_DATA (TYPEINFO_CMT?, DISPLAY_SETTINGS?)>
  <!ATTLIST DEFINED_DATA ADDRESS             CDATA  #REQUIRED>
  <!ATTLIST DEFINED_DATA DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST DEFINED_DATA DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST DEFINED_DATA SIZE                CDATA  #IMPLIED>

<!ELEMENT EQUATES (EQUATE_GROUP*)>

<!ELEMENT EQUATE_GROUP (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?, (EQUATE | BIT_MASK)*)>
  <!ATTLIST EQUATE_GROUP NAME       CDATA       #IMPLIED>
  <!ATTLIST EQUATE_GROUP BIT_FIELD  (yes | no)  #IMPLIED>

<!ELEMENT EQUATE (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST EQUATE NAME     CDATA  #REQUIRED>
  <!ATTLIST EQUATE VALUE    CDATA  #REQUIRED>
  <!ATTLIST EQUATE BIT_MASK CDATA  #IMPLIED>

<!ELEMENT BIT_MASK (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST BIT_MASK NAME   CDATA  #REQUIRED>
  <!ATTLIST BIT_MASK VALUE  CDATA  #REQUIRED>

<!ELEMENT COMMENTS (COMMENT*)>

<!ELEMENT COMMENT (#PCDATA)>
  <!ATTLIST COMMENT ADDRESS  CDATA                                            #REQUIRED>
  <!ATTLIST COMMENT TYPE     (end-of-line | repeatable | pre | post | plate)  #REQUIRED>

<!ELEMENT PROPERTIES (PROPERTY*)>

<!ELEMENT PROPERTY EMPTY>
  <!ATTLIST PROPERTY NAME     CDATA                                                #REQUIRED>
  <!ATTLIST PROPERTY ADDRESS  CDATA                                                #IMPLIED>
  <!ATTLIST PROPERTY TYPE     (string | long | int | double | void | bool | date | custom)  #IMPLIED>
  <!ATTLIST PROPERTY VALUE    CDATA                                                #IMPLIED>

<!ELEMENT BOOKMARKS (BOOKMARK*)>

<!ELEMENT BOOKMARK EMPTY>
  <!ATTLIST BOOKMARK ADDRESS     CDATA  #REQUIRED>
  <!ATTLIST BOOKMARK TYPE        CDATA  #IMPLIED>
  <!ATTLIST BOOKMARK CATEGORY    CDATA  #IMPLIED>
  <!ATTLIST BOOKMARK DESCRIPTION CDATA  #IMPLIED>

<!ELEMENT PROGRAM_TREES (TREE*)>

<!ELEMENT TREE ((FOLDER | FRAGMENT)*)>
  <!ATTLIST TREE NAME CDATA #REQUIRED>

<!ELEMENT FOLDER ((FOLDER | FRAGMENT)*)>
  <!ATTLIST FOLDER NAME CDATA #REQUIRED>

<!ELEMENT FRAGMENT (ADDRESS_RANGE)*>
  <!ATTLIST FRAGMENT NAME CDATA #REQUIRED>

<!ELEMENT ADDRESS_RANGE EMPTY>
  <!ATTLIST ADDRESS_RANGE START  CDATA  #REQUIRED>
  <!ATTLIST ADDRESS_RANGE END    CDATA  #REQUIRED>

<!ELEMENT PROGRAM_ENTRY_POINTS (PROGRAM_ENTRY_POINT*)>

<!ELEMENT PROGRAM_ENTRY_POINT EMPTY>
  <!ATTLIST PROGRAM_ENTRY_POINT  ADDRESS  CDATA  #REQUIRED>

<!ELEMENT RELOCATION_TABLE (RELOCATION*)>

<!ELEMENT RELOCATION EMPTY>
  <!ATTLIST RELOCATION ADDRESS  	CDATA	#REQUIRED>
  <!ATTLIST RELOCATION STATUS    	( UNKNOWN | SKIPPED | UNSUPPORTED | FAILURE | PARTIAL | APPLIED | APPLIED_OTHER )	#IMPLIED>
  <!-- STATUS defaults to APPLIED if BYTES specified and TYPE is non-zero  -->
  <!-- STATUS defaults to APPLIED_OTHER if BYTES specified and TYPE is zero  -->
  <!-- STATUS defaults to UNKNOWN if BYTES are not specified  -->
  <!ATTLIST RELOCATION TYPE     	CDATA	#REQUIRED>
  <!ATTLIST RELOCATION VALUE    	CDATA	#IMPLIED>
  <!ATTLIST RELOCATION BYTES    	CDATA	#IMPLIED>
  <!ATTLIST RELOCATION SYMBOL_NAME	CDATA	#IMPLIED>

<!ELEMENT SYMBOL_TABLE (SYMBOL*)>

<!ELEMENT SYMBOL EMPTY>
  <!ATTLIST SYMBOL ADDRESS   		CDATA            					 #REQUIRED>
  <!ATTLIST SYMBOL NAME      		CDATA             					 #REQUIRED>
  <!ATTLIST SYMBOL NAMESPACE 		CDATA             					 #IMPLIED>
  <!ATTLIST SYMBOL TYPE      		(global | local)  					 #IMPLIED>
  <!ATTLIST SYMBOL SOURCE_TYPE      (USER_DEFINED | IMPORTED | ANALYSIS) #IMPLIED>
  <!ATTLIST SYMBOL PRIMARY   		(y | n)           					 #IMPLIED>
  <!ATTLIST SYMBOL MANGLED   		CDATA             					 #IMPLIED>

<!ELEMENT FUNCTIONS (FUNCTION*)>

<!ELEMENT FUNCTION (RETURN_TYPE?, ADDRESS_RANGE*, REGULAR_CMT?, REPEATABLE_CMT?, TYPEINFO_CMT?, STACK_FRAME?, REGISTER_VAR*)>
  <!ATTLIST FUNCTION ENTRY_POINT       CDATA   #REQUIRED>
  <!ATTLIST FUNCTION NAME              CDATA   #IMPLIED>
  <!-- TODO: create xml attrs for each known attribute type -->
  <!ATTLIST FUNCTION LIBRARY_FUNCTION  (y | n) #IMPLIED>

<!ELEMENT RETURN_TYPE EMPTY>
  <!ATTLIST RETURN_TYPE DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST RETURN_TYPE DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST RETURN_TYPE SIZE                CDATA  #IMPLIED>

<!ELEMENT STACK_FRAME (STACK_VAR*)>
  <!ATTLIST STACK_FRAME LOCAL_VAR_SIZE         CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME PARAM_OFFSET           CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME REGISTER_SAVE_SIZE     CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME RETURN_ADDR_SIZE       CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME BYTES_PURGED           CDATA    #IMPLIED>

<!ELEMENT STACK_VAR (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST STACK_VAR STACK_PTR_OFFSET    CDATA  #REQUIRED> <!-- offset from the stack ptr value at function entry -->
  <!ATTLIST STACK_VAR FRAME_PTR_OFFSET    CDATA  #IMPLIED>
  <!ATTLIST STACK_VAR NAME                CDATA  #IMPLIED>
  <!ATTLIST STACK_VAR DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST STACK_VAR DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST STACK_VAR SIZE                CDATA  #IMPLIED>

<!ELEMENT REGISTER_VAR (REGULAR_CMT?)>
  <!ATTLIST REGISTER_VAR NAME                CDATA  #REQUIRED>
  <!ATTLIST REGISTER_VAR REGISTER            CDATA  #REQUIRED>
  <!ATTLIST REGISTER_VAR DATATYPE            CDATA  #IMPLIED>
  <!ATTLIST REGISTER_VAR DATATYPE_NAMESPACE  CDATA  #IMPLIED>

<!ELEMENT MARKUP (MEMORY_REFERENCE      |
                  STACK_REFERENCE       |
                  EXT_LIBRARY_REFERENCE |
                  EQUATE_REFERENCE      |
                  MANUAL_OPERAND        |
                  MANUAL_INSTRUCTION)*>

<!-- An OPERAND_INDEX is omitted for a mnemonic reference    -->
<!-- The first operand is identified with OPERAND_INDEX=0 -->
<!ELEMENT MEMORY_REFERENCE EMPTY>
  <!ATTLIST MEMORY_REFERENCE ADDRESS        CDATA    #REQUIRED>
  <!ATTLIST MEMORY_REFERENCE OPERAND_INDEX  CDATA    #IMPLIED>
  <!ATTLIST MEMORY_REFERENCE USER_DEFINED   (y | n)  #IMPLIED>
  <!ATTLIST MEMORY_REFERENCE TO_ADDRESS     CDATA    #REQUIRED>
  <!ATTLIST MEMORY_REFERENCE BASE_ADDRESS   CDATA    #IMPLIED>
  <!ATTLIST MEMORY_REFERENCE PRIMARY        (y | n)  #IMPLIED>

<!ELEMENT STACK_REFERENCE EMPTY>
  <!ATTLIST STACK_REFERENCE ADDRESS          CDATA    #REQUIRED>
  <!ATTLIST STACK_REFERENCE OPERAND_INDEX    CDATA    #IMPLIED>
  <!ATTLIST STACK_REFERENCE USER_DEFINED     (y | n)  #IMPLIED>
  <!ATTLIST STACK_REFERENCE STACK_PTR_OFFSET CDATA    #REQUIRED> <!-- offset from the stack ptr value at function entry -->
  <!ATTLIST STACK_REFERENCE FRAME_PTR_OFFSET CDATA    #IMPLIED>

<!ELEMENT EXT_LIBRARY_REFERENCE EMPTY>
  <!ATTLIST EXT_LIBRARY_REFERENCE ADDRESS        CDATA    #REQUIRED>
  <!ATTLIST EXT_LIBRARY_REFERENCE OPERAND_INDEX  CDATA    #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE USER_DEFINED   (y | n)  #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_PROG_NAME  CDATA    #REQUIRED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_LABEL      CDATA    #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_ORDINAL    CDATA    #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_ADDR       CDATA    #IMPLIED>

<!ELEMENT EQUATE_REFERENCE EMPTY>
  <!ATTLIST EQUATE_REFERENCE ADDRESS        CDATA  #REQUIRED>
  <!ATTLIST EQUATE_REFERENCE OPERAND_INDEX  CDATA  #IMPLIED>
  <!ATTLIST EQUATE_REFERENCE NAME           CDATA  #REQUIRED>
  <!ATTLIST EQUATE_REFERENCE VALUE          CDATA  #IMPLIED>

<!ELEMENT MANUAL_OPERAND (#PCDATA)>
  <!ATTLIST MANUAL_OPERAND ADDRESS        CDATA  #REQUIRED>
  <!ATTLIST MANUAL_OPERAND OPERAND_INDEX  CDATA  #REQUIRED>

<!ELEMENT MANUAL_INSTRUCTION (#PCDATA)>
  <!ATTLIST MANUAL_INSTRUCTION ADDRESS CDATA #REQUIRED>

<!ELEMENT EXT_LIBRARY_TABLE (EXT_LIBRARY*)>

<!ELEMENT EXT_LIBRARY EMPTY>
  <!ATTLIST EXT_LIBRARY NAME  CDATA  #REQUIRED>
  <!ATTLIST EXT_LIBRARY PATH  CDATA  #IMPLIED>

<!-- ************************************************************* -->
<!--                                                               -->
<!--                Data DTD                                       -->
<!--                                                               -->
<!-- ************************************************************* -->

<!ELEMENT DATATYPES (STRUCTURE | UNION | FUNCTION_DEF | ENUM | TYPE_DEF)*>

<!ELEMENT MEMBER (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?)>
  <!ATTLIST MEMBER OFFSET              CDATA  #REQUIRED>
  <!ATTLIST MEMBER DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST MEMBER DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST MEMBER NAME                CDATA  #IMPLIED>
  <!ATTLIST MEMBER SIZE                CDATA  #IMPLIED>

<!ELEMENT STRUCTURE (REGULAR_CMT?, REPEATABLE_CMT?, MEMBER*)>
  <!ATTLIST STRUCTURE NAME             CDATA   #REQUIRED>
  <!ATTLIST STRUCTURE NAMESPACE        CDATA   #IMPLIED>
  <!ATTLIST STRUCTURE SIZE             CDATA   #IMPLIED>
  <!ATTLIST STRUCTURE VARIABLE_LENGTH  (y | n) #IMPLIED>

<!ELEMENT UNION (REGULAR_CMT?, REPEATABLE_CMT?, MEMBER*)>
  <!ATTLIST UNION NAME       CDATA  #REQUIRED>
  <!ATTLIST UNION NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST UNION SIZE       CDATA  #IMPLIED>

<!ELEMENT FUNCTION_DEF (REGULAR_CMT?, REPEATABLE_CMT?, RETURN_TYPE?, PARAMETER*)>
  <!ATTLIST FUNCTION_DEF NAME       CDATA  #REQUIRED>
  <!ATTLIST FUNCTION_DEF NAMESPACE  CDATA  #IMPLIED>

<!ELEMENT PARAMETER (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?)>
  <!ATTLIST PARAMETER ORDINAL             CDATA  #REQUIRED>
  <!ATTLIST PARAMETER DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST PARAMETER DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST PARAMETER NAME                CDATA  #IMPLIED>
  <!ATTLIST PARAMETER SIZE                CDATA  #IMPLIED>

<!ELEMENT TYPE_DEF (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST TYPE_DEF NAME                CDATA #REQUIRED>
  <!ATTLIST TYPE_DEF NAMESPACE           CDATA #IMPLIED>
  <!ATTLIST TYPE_DEF DATATYPE            CDATA #REQUIRED>
  <!ATTLIST TYPE_DEF DATATYPE_NAMESPACE  CDATA #IMPLIED>

<!ELEMENT ENUM (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?, ENUM_ENTRY*)>
  <!ATTLIST ENUM NAME       CDATA  #REQUIRED>
  <!ATTLIST ENUM NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST ENUM SIZE       CDATA  #IMPLIED>

<!ELEMENT ENUM_ENTRY (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST ENUM_ENTRY NAME   	CDATA  #REQUIRED>
  <!ATTLIST ENUM_ENTRY VALUE  	CDATA  #REQUIRED>
  <!ATTLIST ENUM_ENTRY COMMENT  CDATA  #REQUIRED>

]>
<PROGRAM NAME="T20K_Manager_V3.10.bin" EXE_PATH="/home/user/inverter/firmware/T20K_Manager_V3.10_5000.bin" EXE_FORMAT="Raw Binary" IMAGE_BASE="00000000">
    <INFO_SOURCE USER="user" TOOL="Ghidra 11.0.3" TIMESTAMP="Thu May 02 04:45:44 CEST 2024" />
    <PROCESSOR NAME="ARM" LANGUAGE_PROVIDER="ARM:LE:32:Cortex:default" ENDIAN="little" />
    <DATATYPES>
        <STRUCTURE NAME="ADC1" NAMESPACE="/" SIZE="0x50">
            <MEMBER OFFSET="0x0" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="SR" SIZE="0x4">
                <REGULAR_CMT>status register</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x4" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="CR1" SIZE="0x4">
                <REGULAR_CMT>control register 1</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x8" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="CR2" SIZE="0x4">
                <REGULAR_CMT>control register 2</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0xc" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="SMPR1" SIZE="0x4">
                <REGULAR_CMT>sample time register 1</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x10" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="SMPR2" SIZE="0x4">
                <REGULAR_CMT>sample time register 2</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x14" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="JOFR1" SIZE="0x4">
                <REGULAR_CMT>injected channel data offset register
          x</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x18" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="JOFR2" SIZE="0x4">
                <REGULAR_CMT>injected channel data offset register
          x</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x1c" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="JOFR3" SIZE="0x4">
                <REGULAR_CMT>injected channel data offset register
          x</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x20" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="JOFR4" SIZE="0x4">
                <REGULAR_CMT>injected channel data offset register
          x</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x24" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="HTR" SIZE="0x4">
                <REGULAR_CMT>watchdog higher threshold
          register</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x28" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="LTR" SIZE="0x4">
                <REGULAR_CMT>watchdog lower threshold
          register</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x2c" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="SQR1" SIZE="0x4">
                <REGULAR_CMT>regular sequence register 1</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x30" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="SQR2" SIZE="0x4">
                <REGULAR_CMT>regular sequence register 2</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x34" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="SQR3" SIZE="0x4">
                <REGULAR_CMT>regular sequence register 3</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x38" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="JSQR" SIZE="0x4">
                <REGULAR_CMT>injected sequence register</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x3c" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="JDR1" SIZE="0x4">
                <REGULAR_CMT>injected data register x</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x40" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="JDR2" SIZE="0x4">
                <REGULAR_CMT>injected data register x</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x44" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="JDR3" SIZE="0x4">
                <REGULAR_CMT>injected data register x</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x48" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="JDR4" SIZE="0x4">
                <REGULAR_CMT>injected data register x</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x4c" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="DR" SIZE="0x4">
                <REGULAR_CMT>regular data register</REGULAR_CMT>
            </MEMBER>
        </STRUCTURE>
        <STRUCTURE NAME="ADC2" NAMESPACE="/" SIZE="0x50">
            <MEMBER OFFSET="0x0" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="SR" SIZE="0x4">
                <REGULAR_CMT>status register</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x4" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="CR1" SIZE="0x4">
                <REGULAR_CMT>control register 1</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x8" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="CR2" SIZE="0x4">
                <REGULAR_CMT>control register 2</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0xc" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="SMPR1" SIZE="0x4">
                <REGULAR_CMT>sample time register 1</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x10" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="SMPR2" SIZE="0x4">
                <REGULAR_CMT>sample time register 2</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x14" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="JOFR1" SIZE="0x4">
                <REGULAR_CMT>injected channel data offset register
          x</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x18" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="JOFR2" SIZE="0x4">
                <REGULAR_CMT>injected channel data offset register
          x</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x1c" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="JOFR3" SIZE="0x4">
                <REGULAR_CMT>injected channel data offset register
          x</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x20" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="JOFR4" SIZE="0x4">
                <REGULAR_CMT>injected channel data offset register
          x</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x24" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="HTR" SIZE="0x4">
                <REGULAR_CMT>watchdog higher threshold
          register</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x28" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="LTR" SIZE="0x4">
                <REGULAR_CMT>watchdog lower threshold
          register</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x2c" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="SQR1" SIZE="0x4">
                <REGULAR_CMT>regular sequence register 1</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x30" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="SQR2" SIZE="0x4">
                <REGULAR_CMT>regular sequence register 2</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x34" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="SQR3" SIZE="0x4">
                <REGULAR_CMT>regular sequence register 3</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x38" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="JSQR" SIZE="0x4">
                <REGULAR_CMT>injected sequence register</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x3c" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="JDR1" SIZE="0x4">
                <REGULAR_CMT>injected data register x</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x40" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="JDR2" SIZE="0x4">
                <REGULAR_CMT>injected data register x</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x44" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="JDR3" SIZE="0x4">
                <REGULAR_CMT>injected data register x</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x48" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="JDR4" SIZE="0x4">
                <REGULAR_CMT>injected data register x</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x4c" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="DR" SIZE="0x4">
                <REGULAR_CMT>regular data register</REGULAR_CMT>
            </MEMBER>
        </STRUCTURE>
        <STRUCTURE NAME="ADC3" NAMESPACE="/" SIZE="0x50">
            <MEMBER OFFSET="0x0" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="SR" SIZE="0x4">
                <REGULAR_CMT>status register</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x4" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="CR1" SIZE="0x4">
                <REGULAR_CMT>control register 1</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x8" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="CR2" SIZE="0x4">
                <REGULAR_CMT>control register 2</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0xc" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="SMPR1" SIZE="0x4">
                <REGULAR_CMT>sample time register 1</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x10" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="SMPR2" SIZE="0x4">
                <REGULAR_CMT>sample time register 2</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x14" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="JOFR1" SIZE="0x4">
                <REGULAR_CMT>injected channel data offset register
          x</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x18" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="JOFR2" SIZE="0x4">
                <REGULAR_CMT>injected channel data offset register
          x</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x1c" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="JOFR3" SIZE="0x4">
                <REGULAR_CMT>injected channel data offset register
          x</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x20" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="JOFR4" SIZE="0x4">
                <REGULAR_CMT>injected channel data offset register
          x</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x24" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="HTR" SIZE="0x4">
                <REGULAR_CMT>watchdog higher threshold
          register</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x28" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="LTR" SIZE="0x4">
                <REGULAR_CMT>watchdog lower threshold
          register</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x2c" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="SQR1" SIZE="0x4">
                <REGULAR_CMT>regular sequence register 1</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x30" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="SQR2" SIZE="0x4">
                <REGULAR_CMT>regular sequence register 2</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x34" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="SQR3" SIZE="0x4">
                <REGULAR_CMT>regular sequence register 3</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x38" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="JSQR" SIZE="0x4">
                <REGULAR_CMT>injected sequence register</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x3c" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="JDR1" SIZE="0x4">
                <REGULAR_CMT>injected data register x</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x40" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="JDR2" SIZE="0x4">
                <REGULAR_CMT>injected data register x</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x44" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="JDR3" SIZE="0x4">
                <REGULAR_CMT>injected data register x</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x48" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="JDR4" SIZE="0x4">
                <REGULAR_CMT>injected data register x</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x4c" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="DR" SIZE="0x4">
                <REGULAR_CMT>regular data register</REGULAR_CMT>
            </MEMBER>
        </STRUCTURE>
        <STRUCTURE NAME="AFIO" NAMESPACE="/" SIZE="0x20">
            <MEMBER OFFSET="0x0" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="EVCR" SIZE="0x4">
                <REGULAR_CMT>Event Control Register
          (AFIO_EVCR)</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x4" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="MAPR" SIZE="0x4">
                <REGULAR_CMT>AF remap and debug I/O configuration
          register (AFIO_MAPR)</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x8" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="EXTICR1" SIZE="0x4">
                <REGULAR_CMT>External interrupt configuration register 1
          (AFIO_EXTICR1)</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0xc" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="EXTICR2" SIZE="0x4">
                <REGULAR_CMT>External interrupt configuration register 2
          (AFIO_EXTICR2)</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x10" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="EXTICR3" SIZE="0x4">
                <REGULAR_CMT>External interrupt configuration register 3
          (AFIO_EXTICR3)</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x14" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="EXTICR4" SIZE="0x4">
                <REGULAR_CMT>External interrupt configuration register 4
          (AFIO_EXTICR4)</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x18" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x19" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x1a" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x1b" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x1c" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="MAPR2" SIZE="0x4">
                <REGULAR_CMT>AF remap and debug I/O configuration
          register</REGULAR_CMT>
            </MEMBER>
        </STRUCTURE>
        <STRUCTURE NAME="BKP" NAMESPACE="/" SIZE="0xbc">
            <MEMBER OFFSET="0x0" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="DR1" SIZE="0x4">
                <REGULAR_CMT>Backup data register (BKP_DR)</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x4" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="DR2" SIZE="0x4">
                <REGULAR_CMT>Backup data register (BKP_DR)</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x8" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="DR3" SIZE="0x4">
                <REGULAR_CMT>Backup data register (BKP_DR)</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0xc" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="DR4" SIZE="0x4">
                <REGULAR_CMT>Backup data register (BKP_DR)</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x10" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="DR5" SIZE="0x4">
                <REGULAR_CMT>Backup data register (BKP_DR)</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x14" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="DR6" SIZE="0x4">
                <REGULAR_CMT>Backup data register (BKP_DR)</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x18" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="DR7" SIZE="0x4">
                <REGULAR_CMT>Backup data register (BKP_DR)</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x1c" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="DR8" SIZE="0x4">
                <REGULAR_CMT>Backup data register (BKP_DR)</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x20" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="DR9" SIZE="0x4">